# deploy:
#   type: git
#   repo: https://github.com/Jye10032/Myblog.git
#   # example, https://github.com/hexojs/hexojs.github.io
#   branch: gh-pages
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 季叶
subtitle: ''
description: ''
keywords: null
author: John Doe
language: zh-CN
timezone: ''


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
## url: http://localhost:4000/
## url: https://82.156.158.96/
url: https://jye10032.github.io/
permalink: ':year/:month/:day/:hash/'
permalink_defaults:
  urlname: index
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
  root: /
index_generator:
  path: /
  per_page: 10
  order_by: '-date'
# Category & Tag
  default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: mtime
per_page: 10
pagination_dir: page

include: null
exclude: null
ignore: null

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@82.156.158.96:/home/git/repos/blog.git
  branch: master
